module.exports = {
  PRODUCT: 'PRODUCT',
  CATEGORY: 'CATEGORY',
  ORDER: 'ORDER',
  CUSTOMER: 'CUSTOMER',
  WITNESS: 'WITNESS',
  INSTALLMENT_PLAN: 'INSTALLMENT_PLAN',
  INSTALLMENT_PAYMENT: 'INSTALLMENT_PAYMENT',
  INSTALLMENT_SETTING: 'INSTALLMENT_SETTING',
  USER: 'USER',
  TENANT: 'TENANT',
  BRANCH: 'BRANCH',
};
